apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  selector:
    matchLabels:
        name: db
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
        - name: db
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env: 
            - name: MYSQL_DATABASE
              value: "loja"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"  
          volumeMounts:
            - name: volume-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: volume-mysql
          persistentVolumeClaim: 
            claimName: configuracao-mysql
